import os
from pathlib import Path
from typing import Iterator

import pytest
from fastapi.testclient import TestClient

from qa._utils import ensure_backend_on_path
from qa.harness.llm_stub import stubbed_chat

ensure_backend_on_path()
import app.llm.openai_client as openai_client  # noqa: E402
from app.llm import embeddings  # noqa: E402
from app.api.main import app  # noqa: E402

BACKEND_DIR = Path(__file__).resolve().parents[2] / "backend"
LOCAL_ROOT = str(Path(__file__).resolve().parents[2])


@pytest.fixture(scope="session", autouse=True)
def _set_cwd() -> Iterator[None]:
    """
    Ensure the backend directory is the working directory for SQLite paths.
    """
    original = Path.cwd()
    os.chdir(BACKEND_DIR)
    os.environ.setdefault("LLM_MODE", "stub")
    try:
        yield
    finally:
        os.chdir(original)


@pytest.fixture(scope="session")
def client() -> Iterator[TestClient]:
    """
    Provide a FastAPI TestClient with LLM calls stubbed out.
    """
    mp = pytest.MonkeyPatch()

    def fake_generate_reply_from_history(messages, mode: str = "auto", model_override=None, **_: object):
        stub = stubbed_chat(mode, messages)
        return {
            "reply": stub["reply"],
            "model": f"stub-{mode}",
            "tokens_in": stub["tokens_in"],
            "tokens_out": stub["tokens_out"],
            "cost_estimate": stub["cost"],
        }

    mp.setattr(openai_client, "generate_reply_from_history", fake_generate_reply_from_history)
    mp.setattr(openai_client, "get_client", lambda: None)
    mp.setattr(embeddings, "get_embedding", lambda _text, _model=None: [0.0, 1.0, 2.0])

    try:
        yield TestClient(app)
    finally:
        mp.undo()


@pytest.fixture
def project(client: TestClient) -> dict:
    resp = client.post(
        "/projects",
        json={
            "name": f"QA_Project_{os.getpid()}",
            "description": "QA autogenerated project",
            "local_root_path": LOCAL_ROOT,
        },
    )
    assert resp.status_code == 200, resp.text
    return resp.json()

